name: Nightly tests

on:
  schedule:
    - cron: '40 22 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with chrono support
      run: cargo test --features chrono --verbose
